### ISSUE TITLE
Scrambled Slider

### ISSUE THREAD

**Issue by boredland** [Sommerregen/grav-theme-zsimplex#2]
I get this in Firefox and Chrome and on the demo page (http://themes.benjamin-regler.de/zsimplex) as well as on my local install:
![zsimplex_scrambled](https://cloud.githubusercontent.com/assets/4662748/25995559/2b64682a-3713-11e7-8a62-74ae472b6149.png)

**Comment by Sommerregen** [comment]
Hi @boredland ,

thanks. I forgot this issue. Will dig into this.

**EDIT:** Ok, I found the issue. I rearranged the JS and make use of the already loaded jQuery collection builtin by Grav. The demo website is not updated yet, but will be soon. Thanks for reporting this issue 🌻

**Comment by boredland** [comment]
I already did fix it for me by cleaning the assets up, rearranging and updating the ones left. And I think its working better than your current version, since the header works properly:
https://github.com/boredland/grav-theme-zsimplex/commit/3df5e885a08adde2e85a95f8c25d48aca1f49c85

**Comment by Sommerregen** [comment]
Hi @boredland ,

yes my changes were more or like dirty ones, because my attempt wasn't to update the javascript libraries. But yours is also good. I will be happy, if you can create a PR.
