### ISSUE TITLE
Error displaying text on frontpage

### ISSUE THREAD

**Issue by awrog** [Sommerregen/grav-theme-zsimplex#6]
The demo of the Simplex theme (https://themes.benjamin-regler.de/zsimplex) is displayed below: the text gets garbled.

![2017-06-26 13_35_05-grav](https://user-images.githubusercontent.com/12153667/27537548-a67f78d6-5a74-11e7-8b66-01d80ea5059f.png)

**Comment by Sommerregen** [comment]
Dear @awrog ,

I just updated my demo site. The demo you saw was a previous version. Now it is even with the latest release again.

Thanks! 👍
